### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by rahul3103** [kinnik/flask-peewee-heroku-setup#1]
Can you update this.

**Comment by swifthorseman** [comment]
Hi, could you give me any more details?

**Comment by swifthorseman** [comment]
I have just tried and was able to deploy without any modification.  Don't forget to set the environment variable `HEROKU` to `1`.  I have added the instructions in the [README](https://github.com/swifthorseman/flask-peewee-heroku-setup/blob/master/README.md) file.

**Comment by rahul3103** [comment]
I have got a more easy way of doing it.
```
import os
from peewee import Model, CharField, PostgresqlDatabase
from urllib.parse import urlparse
from playhouse.db_url import connect

database = connect(os.environ.get('DATABASE_URL') or 'sqlite:///default.db')


class BaseModel(Model):
    class Meta:
        database = database


class Users(BaseModel):
    name = CharField()
    email = CharField()
```
Hope it helps
